# Generated by Django 4.2.5 on 2023-10-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_setup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
    ]
