# Generated by Django 4.2.6 on 2023-10-06 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_alter_setup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.setup'),
        ),
    ]
