# Generated by Django 4.2.6 on 2023-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_menulink_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
