# Generated by Django 4.2.6 on 2023-10-14 14:41

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_setup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.model_validators.is_png_image]),
        ),
    ]
