# Generated by Django 4.2.6 on 2023-10-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If this field is checked, the page will be displayed publicly.'),
        ),
    ]
